In [1]:
# -*- coding:utf-8 -*-
# 数据预处理
#---* 1 *---数据清洗
import pandas as pd
import numpy as np
from pandas import DataFrame,Series

inputfile1 = 'discdata.xls'
data = pd.read_excel(inputfile1)
data.head()

  SYS_NAME     NAME  TARGET_ID DESCRIPTION ENTITY         VALUE COLLECTTIME
0   财务管理系统  CWXT_DB        184     磁盘已使用大小    C:\  3.427079e+07  2014-10-01
1   财务管理系统  CWXT_DB        184     磁盘已使用大小    D:\  8.026259e+07  2014-10-01
2   财务管理系统  CWXT_DB        183        磁盘容量    C:\  5.232332e+07  2014-10-01
3   财务管理系统  CWXT_DB        183        磁盘容量    D:\  1.572833e+08  2014-10-01
4   财务管理系统  CWXT_DB        184     磁盘已使用大小    C:\  3.432890e+07  2014-10-02

In [2]:
# 一般情况下默认磁盘容量是定值，所以需要剔除磁盘容量重复的数据
data.drop_duplicates(data.columns[:-1],inplace=True)
data.to_excel('dataCleaned.xlsx')
data.head()

  SYS_NAME     NAME  TARGET_ID DESCRIPTION ENTITY         VALUE COLLECTTIME
0   财务管理系统  CWXT_DB        184     磁盘已使用大小    C:\  3.427079e+07  2014-10-01
1   财务管理系统  CWXT_DB        184     磁盘已使用大小    D:\  8.026259e+07  2014-10-01
2   财务管理系统  CWXT_DB        183        磁盘容量    C:\  5.232332e+07  2014-10-01
3   财务管理系统  CWXT_DB        183        磁盘容量    D:\  1.572833e+08  2014-10-01
4   财务管理系统  CWXT_DB        184     磁盘已使用大小    C:\  3.432890e+07  2014-10-02

In [3]:
#---* 2 *---属性构造 
# 思路：由于每台服务器上的这三个属性值一直不变：NAME、TARGET_ID、ENTITY，将这三个属性值合并
inputfile2 = 'dataCleaned.xlsx'
data = pd.read_excel(inputfile2)

In [4]:
# 教材上方法一：
df = data[data['TARGET_ID'] == 184].copy() # 只选取TARGET_ID为184的数据
df_group = df.groupby('COLLECTTIME') # 以时间分组得到一个GroupBy对象

#定义属性变换函数
def attr_trans(x):
    result = Series(index = ['SYS_NAME','CWXT_DB:184:C:\\','CWXT_DB:184:D:\\','COLLECTTIME'])
    result['SYS_NAME'] = x['SYS_NAME'].iloc[0]
    result['COLLECTTIME'] = x['COLLECTTIME'].iloc[0]
    result['CWXT_DB:184:C:\\'] = x['VALUE'].iloc[0]
    result['CWXT_DB:184:D:\\'] = x['VALUE'].iloc[1]
    return result 
    
data_attr_constr = df_group.apply(attr_trans)# 逐组处理
data_attr_constr.to_excel('attrsConstruction.xlsx',index=False)
data_attr_constr

            SYS_NAME  CWXT_DB:184:C:\  CWXT_DB:184:D:\ COLLECTTIME
COLLECTTIME
2014-10-01    财务管理系统      34270787.33      80262592.65  2014-10-01
2014-10-02    财务管理系统      34328899.02      83200151.65  2014-10-02
2014-10-03    财务管理系统      34327553.50      83208320.00  2014-10-03
2014-10-04    财务管理系统      34288672.21      83099271.65  2014-10-04
2014-10-05    财务管理系统      34190978.41      82765171.65  2014-10-05
2014-10-06    财务管理系统      34187614.43      82522895.00  2014-10-06
2014-10-07    财务管理系统      34285280.22      82590885.00  2014-10-07
2014-10-08    财务管理系统      34290578.41      82368173.30  2014-10-08
2014-10-09    财务管理系统      33211870.40      82172263.30  2014-10-09
2014-10-10    财务管理系统      33249253.87      81922685.00  2014-10-10
2014-10-11    财务管理系统      33253832.53      84844722.95  2014-10-11
2014-10-12    财务管理系统      34328058.03      84769868.90  2014-10-12
2014-10-13    财务管理系统      34328674.80      84558703.40  2014-10-13
2014-10-14    财务管理系统      34234933.61      84207166.80  2014-10-14
2014-10-15    财务管理系统      34022726.41      84042911.90  2014-10-15
2014-10-16    财务管理系统      35016309.47      84129516.15  2014-10-16
2014-10-17    财务管理系统      34981412.82      83877754.85  2014-10-17
2014-10-18    财务管理系统      34828871.38      83887520.40  2014-10-18
2014-10-19    财务管理系统      34832868.75      83538509.75  2014-10-19
2014-10-20    财务管理系统      34843372.75      86483653.00  2014-10-20
2014-10-21    财务管理系统      34847749.42      82496743.30  2014-10-21
2014-10-22    财务管理系统      34829775.93      82300356.65  2014-10-22
2014-10-23    财务管理系统      34824290.49      82130251.65  2014-10-23
2014-10-24    财务管理系统      34827149.93      84844587.65  2014-10-24
2014-10-25    财务管理系统      34820088.89      84845444.65  2014-10-25
2014-10-26    财务管理系统      34776030.47      84684911.05  2014-10-26
2014-10-27    财务管理系统      34667722.51      84500606.35  2014-10-27
2014-10-28    财务管理系统      35705011.09      84145461.25  2014-10-28
2014-10-29    财务管理系统      35594215.37      84172525.10  2014-10-29
2014-10-30    财务管理系统      35411287.07      83957818.70  2014-10-30
2014-10-31    财务管理系统      35389055.02      83684789.75  2014-10-31
2014-11-01    财务管理系统      35385076.36      86485366.95  2014-11-01
2014-11-02    财务管理系统      35462038.02      86454023.45  2014-11-02
2014-11-03    财务管理系统      35486821.33      86127041.70  2014-11-03
2014-11-04    财务管理系统      35471088.77      86161390.40  2014-11-04
2014-11-05    财务管理系统      35547564.55      85938933.90  2014-11-05
2014-11-06    财务管理系统      35606941.11      85645056.50  2014-11-06
2014-11-07    财务管理系统      35546714.13      85272926.05  2014-11-07
2014-11-08    财务管理系统      35510966.73      88110097.75  2014-11-08
2014-11-09    财务管理系统      35491498.51      88128626.65  2014-11-09
2014-11-10    财务管理系统      35601990.55      88075997.75  2014-11-10
2014-11-11    财务管理系统      35687972.60      87753526.65  2014-11-11
2014-11-12    财务管理系统      35704312.58      87249335.55  2014-11-12
2014-11-13    财务管理系统      35704980.73      86986142.20  2014-11-13
2014-11-14    财务管理系统      34570385.45      86678240.00  2014-11-14
2014-11-15    财务管理系统      34673820.69      89766600.00  2014-11-15
2014-11-16    财务管理系统      34793245.31      89377527.25  2014-11-16

In [5]:
#方法二，死方法，没有方法一灵活
df_g = df.groupby('COLLECTTIME').size()
indexpre = df_g.index
data_processed = DataFrame([],index = indexpre, columns=['SYS_NAME','CWXT_DB:184:C:\\','CWXT_DB:184:D:\\'])
data_processed['SYS_NAME'] =  u'财务管理系统'
data_processed['CWXT_DB:184:C:\\'] = df['VALUE'][df['ENTITY']=='C:\\'].values
data_processed['CWXT_DB:184:D:\\'] = df['VALUE'][df['ENTITY']=='D:\\'].values
data_processed.head()

            SYS_NAME  CWXT_DB:184:C:\  CWXT_DB:184:D:\
COLLECTTIME
2014-10-01    财务管理系统      34270787.33      80262592.65
2014-10-02    财务管理系统      34328899.02      83200151.65
2014-10-03    财务管理系统      34327553.50      83208320.00
2014-10-04    财务管理系统      34288672.21      83099271.65
2014-10-05    财务管理系统      34190978.41      82765171.65